# 답안 작성 방법

아래 이미지에서 "더블클릭 또는 Enter키를 눌러 수정"을 누르신후 해당 창에 답을 적으시면 됩니다.

![image](https://github.com/user-attachments/assets/2aa2ff05-fb0e-4f00-a121-78afeaad4f09)

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

# 07차시 과제

### Q1. 길이가 5인 1차원 텐서를 만들어 보세요. 이 텐서의 모든 원소는 1로 초기화되어야 합니다.

In [1]:
import torch

# 길이가 5인 1차원 텐서 생성, 모든 원소를 1로 초기화
tensor = torch.ones(5)

# 결과 출력
print(tensor)

tensor([1., 1., 1., 1., 1.])


### Q2. 3x3 크기의 2차원 텐서를 생성하고, 모든 원소를 0으로 초기화하세요.

In [2]:
import torch

# 길이가 5인 1차원 텐서 생성, 모든 원소를 1로 초기화
tensor = torch.zeros(3,3)

# 결과 출력
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Q3. 두 개의 텐서 a와 b를 만들어 각각 2x2 크기로 초기화하고, 이 두 텐서를 더해보세요

In [5]:
import torch

# 2x2 크기의 랜덤 텐서 a와 b를 생성 (정규 분포에서 랜덤 값)
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

# 두 텐서를 더하기
result = a + b

# 결과 출력
print("Tensor a:\n", a)
print("Tensor b:\n", b)
print("a + b:\n", result)


Tensor a:
 tensor([[1, 2],
        [3, 4]])
Tensor b:
 tensor([[5, 6],
        [7, 8]])
a + b:
 tensor([[ 6,  8],
        [10, 12]])


### Q4. 다음은 PyTorch를 사용하여 자동 미분을 수행하려는 코드이다. 그러나 코드에는 오류가 있다. 해당 오류를 수정하여 올바르게 자동 미분을 수행하라.


In [11]:
import torch

x = torch.tensor([1, 2, 3],dtype=torch.float32,requires_grad=True)
y = torch.tensor([4, 5, 6],dtype=torch.float32)

z = torch.sum(x * y)

loss =z
loss.backward()

x.grad

tensor([4., 5., 6.])

### Q5. torch의 zero_grad 함수는 무엇이며, 어떠한 역할을 하는가? 그리고 만약 zero_grad를 호출하지 않으면 어떤 문제가 발생하는가?

그라디언트를 초기화해주는 함수이다.
초기화를 해주지 않으면 그라디언트가 누적이 되어서 제대로 학습이 되지 않을 수 있다.

### Q6. torch의 MSE함수를 이용하여 제공된 두 텐서(A, B)의 mean square error를 구하시오.

In [14]:
import torch

A = torch.tensor([[1, 2], [3, 4]],dtype = torch.float32)
B = torch.tensor([[5, 6], [7, 8]],dtype = torch.float32)

# MSE Loss

loss = torch.nn.MSELoss()(A, B)
# Write your code here
loss

tensor(16.)

### Q7.  K-means 클러스터링이 무엇이고, 각 알고리즘의 주요 단계들을 설명하라.


K-means 클러스터링은 비지도 학습 알고리즘 중 하나로, 주어진 데이터셋을 K개의 군집으로 나누는 데 사용한다.

주요 단계는 K 값 설정, 초기 중심점 선택, 할당 단계, 중심점 업데이트 단계,반복으로 구성되어 있다.