# Vector 연산

In [ ]:
import numpy as np

In [ ]:
# numpy 사용여부
# scalar 연산, vector 연산, matrix 연산
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    #b =  1.2   # all 1
    #b =  1.1   # all 1
    #b =  1.0   # nand
    #b =  0.9   # nand
    #b =  0.8   # nand
    b =  0.7   # nand original
    #b =  0.6   # nand
    #b =  0.5   # nor
    #b =  0.4   # nor
    #b =  0.3   # nor
    #b =  0.2   # nor
    #b =  0.1   # nor
    #b = -0.0   # all 0
    #b = -0.1   # all 0
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [ ]:
for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = NAND(xs[0], xs[1])
    print(str(xs) + " -> " + str(y))

(0, 0) -> 1
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0


In [ ]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [ ]:
for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = OR(xs[0], xs[1])
    print(str(xs) + " -> " + str(y))

(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 1


In [ ]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([1, 1])
    b = -1.4
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [ ]:
for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = AND(xs[0], xs[1])
    print(str(xs) + " -> " + str(y))

(0, 0) -> 0
(1, 0) -> 0
(0, 1) -> 0
(1, 1) -> 1


In [ ]:
# coding: utf-8
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)

    y = AND(s1, s2)
    return y

In [ ]:
for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = XOR(xs[0], xs[1])
    print(str(xs) + " -> " + str(y))

(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0


# Matrix 연산

In [ ]:
def NAND_M(X):
    W = np.array([[-0.5], [-0.5]])                     # (2, 1)
    b = np.array([[0.7], [0.7], [0.7], [0.7]])         # (4, 1)
    tmp = np.dot(X,W) + b                              # (4, 1)
    RET = np.array([[0], [0], [0], [0]])
    print(tmp)
    for i, val in enumerate(tmp):
        if val <= 0:
            RET[i] = 0
        else:
            RET[i] = 1
    return RET

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
#print(NAND_M(X))
NAND_M(X)

[[ 0.7]
 [ 0.2]
 [ 0.2]
 [-0.3]]


array([[1],
       [1],
       [1],
       [0]])

In [ ]:
def OR_M(X):
    W = np.array([[0.5], [0.5]])                     # (2, 1)
    b = np.array([[-0.2], [-0.2], [-0.2], [-0.2]])   # (4, 1)
    tmp = np.dot(X,W) + b                            # (4, 1)
    RET = np.array([[0], [0], [0], [0]])
    print(tmp)
    for i, val in enumerate(tmp):
        if val <= 0:
            RET[i] = 0
        else:
            RET[i] = 1
    return RET

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
#print(NAND_M(X))
OR_M(X)

[[-0.2]
 [ 0.3]
 [ 0.3]
 [ 0.8]]


array([[0],
       [1],
       [1],
       [1]])

In [ ]:
def AND_M(X):
    W = np.array([[0.5], [0.5]])                     # (2, 1)
    b = np.array([[-0.7], [-0.7], [-0.7], [-0.7]])   # (4, 1)
    tmp = np.dot(X,W) + b                            # (4, 1)
    RET = np.array([[0], [0], [0], [0]])
    print(tmp)
    for i, val in enumerate(tmp):
        if val <= 0:
            RET[i] = 0
        else:
            RET[i] = 1
    return RET

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
#print(NAND_M(X))
AND_M(X)

[[-0.7]
 [-0.2]
 [-0.2]
 [ 0.3]]


array([[0],
       [0],
       [0],
       [1]])

In [ ]:
def XOR_M(X):
    S1 = NAND_M(X)
    S2 = OR_M(X)
    S = np.concatenate((S1, S2), axis=1)
    y = AND_M(S)
    return y

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
#print(NAND_M(X))
XOR_M(X)

[[ 0.7]
 [ 0.2]
 [ 0.2]
 [-0.3]]
[[-0.2]
 [ 0.3]
 [ 0.3]
 [ 0.8]]
[[-0.2]
 [ 0.3]
 [ 0.3]
 [-0.2]]


array([[0],
       [1],
       [1],
       [0]])

concat 없이 출력

In [ ]:
def NAND_OR_M(X):
    W = np.array([[-0.5, 0.5], [-0.5, 0.5]])                           # (2, 2)
    b = np.array([[0.7, -0.2], [0.7, -0.2], [0.7, -0.2], [0.7, -0.2]]) # (4, 2)
    tmp = np.dot(X,W) + b                                              # (4, 2)
    print(tmp)
    RET = np.array([[0,0], [0,0], [0,0], [0,0]])
    for i, vals in enumerate(tmp):
        for j, val in enumerate(vals):
            if val <= 0:
                RET[i][j] = 0
            else:
                RET[i][j] = 1
    return RET

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
NAND_OR_M(X)

[[ 0.7 -0.2]
 [ 0.2  0.3]
 [ 0.2  0.3]
 [-0.3  0.8]]


array([[1, 0],
       [1, 1],
       [1, 1],
       [0, 1]])

In [ ]:
def XOR_MM(X):
    S = NAND_OR_M(X)
    y = AND_M(S)
    return y

In [ ]:
X=np.array([[0, 0], [1, 0], [0, 1], [1, 1]])  # (4,2)
XOR_MM(X)

[[ 0.7 -0.2]
 [ 0.2  0.3]
 [ 0.2  0.3]
 [-0.3  0.8]]
[[-0.2]
 [ 0.3]
 [ 0.3]
 [-0.2]]


array([[0],
       [1],
       [1],
       [0]])

dictionary 형식으로 정리